### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by jblacker** [opt-tech/redshift-fake-driver#45]
I'm having a strange connection issue when using the driver within integration tests via JUnit.

When I hit the code to connect:
```
Class.forName("jp.ne.opt.redshiftfake.postgres.FakePostgresqlDriver");
 this.connectionProperties = new Properties();
 this.connectionProperties.setProperty("user", "sa");
 this.connectionProperties.setProperty("password", <redacted>);
 this.connectionProperties.setProperty("driver", "jp.ne.opt.redshiftfake.postgres.FakePostgresqlDriver")

Connection conn = DriverManager.getConnection("jdbc:postgresqlredshift://localhost:5432/", this.connectionProperties); // <--- never makes it past this line
```

However, it appears that the error happens somewhere on the threadpool, not on the main thread since the test spins forever without a failure, yet I see this message in the logs:
```
Exception in thread "Thread-5" java.lang.AssertionError
	at com.amazon.support.exceptions.ErrorException.getMessage(Unknown Source)
	at com.amazon.redshift.client.InboundDataHandler.read(InboundDataHandler.java:700)
	at com.amazon.support.channels.AbstractSocketChannel.readCallback(Unknown Source)
	at com.amazon.support.channels.PlainSocketChannel.read(Unknown Source)
	at com.amazon.jdbc.communications.InboundMessagesThread.run(InboundMessagesThread.java:349)
```

Not sure what would cause this, but I have no issues when connecting to real RedShift.

System Details:
 - Postgres DB being used via the official docker container (latest version)
 - Postgres Driver configured via Gradle: `'org.postgresql:postgresql:42.2.5'`
 - Java 1.8
 - AWS SDK 1.11.450

**Comment by jblacker** [comment]
Nevermind, I was having in issue with mismatched AWS SDKs.
