### ISSUE TITLE
Unload command not working

### ISSUE THREAD

**Issue by cenacsf** [opt-tech/redshift-fake-driver#55]
Version i tried: 1.0.13

`  val url = "jdbc:postgresqlredshift://localhost:5432/xxx"
  val prop = new Properties ()
  prop.setProperty ("driver", "jp.ne.opt.redshiftfake.postgres.FakePostgresqlDriver")
  prop.setProperty ("user", "abc")
  prop.put("password", "def")
  Class.forName ("jp.ne.opt.redshiftfake.postgres.FakePostgresqlDriver")
  val conn = DriverManager.getConnection (url, prop)
  val stmt = conn.createStatement ()

  val command =
    s"""
       |UNLOAD ('${"""SELECT * FROM table1"""}') TO 'http://localhost:4572/demo-bucket1'
       |CREDENTIALS 'aws_access_key_id=AKIAXXXXXXXXXXXXXXX;aws_secret_access_key=YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY';
       |""".stripMargin
  stmt.execute(command)`

I get following error when i run

 one is undefined.
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: syntax error at or near "UNLOAD"
  Position: 2
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2458)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2158)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:291)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:432)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:358)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:305)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:291)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:269)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:265)
	at jp.ne.opt.redshiftfake.FakeStatement$$anonfun$execute$1.apply$mcZ$sp(FakeStatement.scala:72)
	at jp.ne.opt.redshiftfake.FakeStatement$$anonfun$execute$1.apply(FakeStatement.scala:72)
	at jp.ne.opt.redshiftfake.FakeStatement$$anonfun$execute$1.apply(FakeStatement.scala:72)

**Comment by cenacsf** [comment]
ignore no longer issue , issue was s3 endpoint not properly set
