### ISSUE TITLE
jawn.IncompleteParseException: exhausted input

### ISSUE THREAD

**Issue by peterlitvak** [opt-tech/redshift-fake-driver#61]
```
Caused by: jawn.IncompleteParseException: exhausted input
	at jawn.Parser.parse(Parser.scala:362)
	at jawn.SyncParser.parse(SyncParser.scala:24)
	at jawn.ast.JParser$$anonfun$parseFromString$1.apply(JParser.scala:16)
	at jawn.ast.JParser$$anonfun$parseFromString$1.apply(JParser.scala:16)
	at scala.util.Try$.apply(Try.scala:192)
	at jawn.ast.JParser$.parseFromString(JParser.scala:16)
	at jp.ne.opt.redshiftfake.read.Jsonpaths$IndexedReader.<init>(Jsonpaths.scala:41)
	at jp.ne.opt.redshiftfake.read.Jsonpaths.mkReader(Jsonpaths.scala:59)
	at jp.ne.opt.redshiftfake.read.Reader$$anonfun$read$1$$anonfun$apply$1.apply(Reader.scala:32)
	at jp.ne.opt.redshiftfake.read.Reader$$anonfun$read$1$$anonfun$apply$1.apply(Reader.scala:30)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:732)
	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:708)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at jp.ne.opt.redshiftfake.read.Reader.read(Reader.scala:37)
	at jp.ne.opt.redshiftfake.CopyInterceptor$class.executeCopy(Interceptor.scala:31)
	at jp.ne.opt.redshiftfake.FakeStatement.executeCopy(FakeStatement.scala:22)
	at jp.ne.opt.redshiftfake.FakeStatement$$anonfun$switchExecute$1.apply(FakeStatement.scala:121)
	at jp.ne.opt.redshiftfake.FakeStatement$$anonfun$switchExecute$1.apply(FakeStatement.scala:120)
	at scala.Option.map(Option.scala:146)
	at jp.ne.opt.redshiftfake.FakeStatement.switchExecute(FakeStatement.scala:120)
	at jp.ne.opt.redshiftfake.FakeStatement.execute(FakeStatement.scala:72)
	at io.smartvid.service.repository.analytics.AnalyticsService.upsert(AnalyticsService.java:205)
	at io.smartvid.service.repository.analytics.AnalyticsService.upsert(AnalyticsService.java:135)
	... 31 more
```

**Comment by peterlitvak** [comment]
related to https://github.com/opt-tech/redshift-fake-driver/issues/62
